from addict import Dict

DriverErrorCodes = Dict(
    VEHICLE_REGISTRATION_ERROR="VEHICLE_REGISTRATION_ERROR",
    VEHICLE_NOT_FOUND_ERROR="VEHICLE_NOT_FOUND_ERROR",
    LICENSE_NUMBER_INVALID_ERROR="LICENSE_NUMBER_INVALID_ERROR",
    PLATE_NUMBER_INVALID_ERROR="PLATE_NUMBER_INVALID_ERROR",
    DUPLICATE_VEHICLE_ERROR="DUPLICATE_VEHICLE_ERROR",
    VEHICLE_VALIDATION_ERROR="VEHICLE_VALIDATION_ERROR"
)