from .base import Dict


UserErrorCodes = Dict(
    ADDRESS_NOT_FOUND_ERROR="ADDRESS_NOT_FOUND_ERROR",
    UPDATE_ADDRESS_ERROR="UPDATE_ADDRESS_ERROR",
    GET_ADDRESS_ERROR="GET_ADDRESS_ERROR",
    GET_ADDRESS_INFO_ERROR="GET_ADDRESS_INFO_ERROR",
    GET_ADDRESSES_ERROR="GET_ADDRESSES_ERROR",
    ADD_ADDRESS_ERROR="ADD_ADDRESS_ERROR",
    DELETE_ADDRESS_ERROR="DELETE_ADDRESS_ERROR",
    DEFAULT_ADDRESS_DELETION_ERROR="DEFAULT_ADDRESS_DELETION_ERROR",
    ADDRESS_VALIDATION_ERROR="ADDRESS_VALIDATION_ERROR",
    ADDRESS_PERMISSION_DENIED_ERROR="ADDRESS_PERMISSION_DENIED_ERROR",
    DUPLICATE_ADDRESS_ERROR="DUPLICATE_ADDRESS_ERROR",
    ADDRESS_SERVICE_UNAVAILABLE_ERROR="ADDRESS_SERVICE_UNAVAILABLE_ERROR"

    USER_REGISTRATION_ERROR="USER_REGISTRATION_ERROR",
    USER_PROFILE_UPDATE_ERROR="USER_PROFILE_UPDATE_ERROR",
    USER_LOGIN_ERROR="USER_LOGIN_ERROR",
    USER_DELETE_ACCOUNT_ERROR="USER_DELETE_ACCOUNT_ERROR",
    USER_VERIFICATION_ERROR="USER_VERIFICATION_ERROR",
    USER_LOGOUT_ERROR="USER_LOGOUT_ERROR",
    USER_NOT_FOUND_ERROR="USER_NOT_FOUND_ERROR",
    USER_NOT_VERIFIED_ERROR="USER_NOT_VERIFIED_ERROR",
    ACCOUNT_EXISTS_ERROR="ACCOUNT_EXISTS_ERROR",
    MISSING_NATIONAL_ID_ERROR="MISSING_NATIONAL_ID_ERROR",
    INVALID_AUTHENTICATION_CODE_ERROR="INVALID_AUTHENTICATION_CODE_ERROR",
    WRONG_AUTHENTICATION_CODE_ERROR="WRONG_AUTHENTICATION_CODE_ERROR",
    WRONG_PASSWORD_ERROR="WRONG_PASSWORD_ERROR",
    USER_ALREADY_VERIFIED_ERROR="USER_ALREADY_VERIFIED_ERROR",
    USER_LOCKED_OUT_ERROR="USER_LOCKED_OUT_ERROR",
    USER_SESSION_EXPIRED_ERROR="USER_SESSION_EXPIRED_ERROR",
    USER_PERMISSION_DENIED_ERROR="USER_PERMISSION_DENIED_ERROR",
    USER_PASSWORD_RESET_ERROR="USER_PASSWORD_RESET_ERROR",
    USER_PASSWORD_EXPIRED_ERROR="USER_PASSWORD_EXPIRED_ERROR",
    USER_DUPLICATE_EMAIL_ERROR="USER_DUPLICATE_EMAIL_ERROR",
    USER_EMAIL_NOT_FOUND_ERROR="USER_EMAIL_NOT_FOUND_ERROR",
    USER_SERVICE_UNAVAILABLE_ERROR="USER_SERVICE_UNAVAILABLE_ERROR"
)