from .base import Dict

ValidationErrorCodes = Dict(
    MISSING_PHONE_NUMBER_ERROR="MISSING_PHONE_NUMBER_ERROR",
    INVALID_PHONE_NUMBER_ERROR="INVALID_PHONE_NUMBER_ERROR",
    MISSING_NATIONAL_ID_ERROR="MISSING_NATIONAL_ID_ERROR",
    INVALID_NATIONAL_ID_ERROR="INVALID_NATIONAL_ID_ERROR",
    MISSING_PASSWORD_ERROR="MISSING_PASSWORD_ERROR",
    INVALID_PASSWORD_ERROR="INVALID_PASSWORD_ERROR",
    MISSING_ROLE_ERROR="MISSING_ROLE_ERROR",
    INVALID_ROLE_ERROR="INVALID_ROLE_ERROR",
    MISSING_EMAIL_ERROR="MISSING_EMAIL_ERROR",
    INVALID_EMAIL_ERROR="INVALID_EMAIL_ERROR",
)
