class ErrorCodes:
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # Field Validation Errors
    MISSING_PHONE_NUMBER_ERROR="MISSING_PHONE_NUMBER_ERROR",
    INVALID_PHONE_NUMBER_ERROR="INVALID_PHONE_NUMBER_ERROR",
    MISSING_NATIONAL_ID_ERROR="MISSING_NATIONAL_ID_ERROR",
    INVALID_NATIONAL_ID_ERROR="INVALID_NATIONAL_ID_ERROR",
    MISSING_PASSWORD_ERROR="MISSING_PASSWORD_ERROR",
    INVALID_PASSWORD_ERROR="INVALID_PASSWORD_ERROR",
    MISSING_ROLE_ERROR="MISSING_ROLE_ERROR",
    INVALID_ROLE_ERROR="INVALID_ROLE_ERROR",
    MISSING_EMAIL_ERROR="MISSING_EMAIL_ERROR",
    INVALID_EMAIL_ERROR="INVALID_EMAIL_ERROR"

    # Address CRUD
    ADDRESS_NOT_FOUND_ERROR = "ADDRESS_NOT_FOUND_ERROR"
    UPDATE_ADDRESS_ERROR = "UPDATE_ADDRESS_ERROR"
    GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR"
    GET_ADDRESS_INFO_ERROR = "GET_ADDRESS_INFO_ERROR"
    GET_ADDRESSES_ERROR = "GET_ADDRESSES_ERROR"
    ADD_ADDRESS_ERROR = "ADD_ADDRESS_ERROR"
    DELETE_ADDRESS_ERROR = "DELETE_ADDRESS_ERROR"
    DEFAULT_ADDRESS_DELETION_ERROR = "DEFAULT_ADDRESS_DELETION_ERROR"
    ADDRESS_VALIDATION_ERROR = "ADDRESS_VALIDATION_ERROR"
    ADDRESS_PERMISSION_DENIED_ERROR = "ADDRESS_PERMISSION_DENIED_ERROR"
    DUPLICATE_ADDRESS_ERROR = "DUPLICATE_ADDRESS_ERROR"
    ADDRESS_SERVICE_UNAVAILABLE_ERROR = "ADDRESS_SERVICE_UNAVAILABLE_ERROR"

    # User CRUD Errors
    USER_REGISTRATION_ERROR = "USER_REGISTRATION_ERROR"
    USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR"
    USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
    USER_DELETE_ACCOUNT_ERROR = "USER_DELETE_ACCOUNT_ERROR"
    USER_VERIFICATION_ERROR = "USER_VERIFICATION_ERROR"
    USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR"
    USER_LOAD_ACCOUNT_ERROR = "USER_LOAD_ACCOUNT_ERROR"
    USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR"
    USER_NOT_VERIFIED_ERROR = "USER_NOT_VERIFIED_ERROR"
    ACCOUNT_EXISTS_ERROR = "ACCOUNT_EXISTS_ERROR"
    INVALID_AUTHENTICATION_CODE_ERROR = "INVALID_AUTHENTICATION_CODE_ERROR"
    WRONG_AUTHENTICATION_CODE_ERROR = "WRONG_AUTHENTICATION_CODE_ERROR"
    WRONG_PASSWORD_ERROR = "WRONG_PASSWORD_ERROR"
    RESENDING_AUTHENTICATION_CODE_ERROR = "RESENDING_AUTHENTICATION_CODE_ERROR"
    USER_ALREADY_VERIFIED_ERROR = "USER_ALREADY_VERIFIED_ERROR"
    USER_LOCKED_OUT_ERROR = "USER_LOCKED_OUT_ERROR"
    USER_SESSION_EXPIRED_ERROR = "USER_SESSION_EXPIRED_ERROR"
    USER_PERMISSION_DENIED_ERROR = "USER_PERMISSION_DENIED_ERROR"
    USER_PASSWORD_RESET_ERROR = "USER_PASSWORD_RESET_ERROR"
    USER_PASSWORD_EXPIRED_ERROR = "USER_PASSWORD_EXPIRED_ERROR"
    USER_DUPLICATE_EMAIL_ERROR = "USER_DUPLICATE_EMAIL_ERROR"
    USER_EMAIL_NOT_FOUND_ERROR = "USER_EMAIL_NOT_FOUND_ERROR"
    USER_SERVICE_UNAVAILABLE_ERROR = "USER_SERVICE_UNAVAILABLE_ERROR"

    # DB Errors
    DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
    DB_TRANSACTION_ERROR = "DB_TRANSACTION_ERROR"
    DB_SESSION_CREATION_ERROR = "DB_SESSION_CREATION_ERROR"
    DB_INSERT_ERROR = "DB_INSERT_ERROR"
    DB_FETCH_ERROR = "DB_FETCH_ERROR"
    DB_UPDATE_ERROR = "DB_UPDATE_ERROR"
    DB_JOIN_ERROR = "DB_JOIN_ERROR"
    DB_DELETE_ERROR = "DB_DELETE_ERROR"
    DB_DUPLICATE_ENTRY_ERROR = "DB_DUPLICATE_ENTRY_ERROR"
    DB_CONSTRAINT_VIOLATION_ERROR = "DB_CONSTRAINT_VIOLATION_ERROR"
    DB_TIMEOUT_ERROR = "DB_TIMEOUT_ERROR"
    DB_INVALID_QUERY_ERROR = "DB_INVALID_QUERY_ERROR"

    # Cache Errors
    CACHE_CONNECTION_ERROR = "CACHE_CONNECTION_ERROR"
    CACHE_TRANSACTION_ERROR = "CACHE_TRANSACTION_ERROR"
    CACHE_SESSION_CREATION_ERROR = "CACHE_SESSION_CREATION_ERROR"
    CACHE_FETCH_ERROR = "CACHE_FETCH_ERROR"
    CACHE_INSERT_ERROR = "CACHE_INSERT_ERROR"
    CACHE_DELETE_ERROR = "CACHE_DELETE_ERROR"
    CACHE_EXPIRE_ERROR = "CACHE_EXPIRE_ERROR"
    CACHE_PIPELINE_ERROR = "CACHE_PIPELINE_ERROR"
    CACHE_FLUSH_ERROR = "CACHE_FLUSH_ERROR"
    CACHE_KEY_NOT_FOUND_ERROR = "CACHE_KEY_NOT_FOUND_ERROR"
    CACHE_TIMEOUT_ERROR = "CACHE_TIMEOUT_ERROR"
    CACHE_INVALID_COMMAND_ERROR = "CACHE_INVALID_COMMAND_ERROR"
    CACHE_AUTHENTICATION_ERROR = "CACHE_AUTHENTICATION_ERROR"

    # Message Broker Errors
    RABBITMQ_CONNECTION_ERROR = "RABBITMQ_CONNECTION_ERROR"
    RABBITMQ_CHANNEL_ERROR = "RABBITMQ_CHANNEL_ERROR"
    RABBITMQ_EXCHANGE_ERROR = "RABBITMQ_EXCHANGE_ERROR"
    RABBITMQ_QUEUE_ERROR = "RABBITMQ_QUEUE_ERROR"
    RABBITMQ_PUBLISH_ERROR = "RABBITMQ_PUBLISH_ERROR"
    RABBITMQ_CONSUME_ERROR = "RABBITMQ_CONSUME_ERROR"
    RABBITMQ_ACK_ERROR = "RABBITMQ_ACK_ERROR"
    RABBITMQ_NACK_ERROR = "RABBITMQ_NACK_ERROR"
    RABBITMQ_RPC_ERROR = "RABBITMQ_RPC_ERROR"
    RABBITMQ_TIMEOUT_ERROR = "RABBITMQ_TIMEOUT_ERROR"
    RABBITMQ_AUTHENTICATION_ERROR = "RABBITMQ_AUTHENTICATION_ERROR"

    # Event Errors
    EVENT_CONNECTION_ERROR = "EVENT_CONNECTION_ERROR"
    EVENT_PUBLISH_ERROR = "EVENT_PUBLISH_ERROR"
    EVENT_CONSUME_ERROR = "EVENT_CONSUME_ERROR"
    EVENT_TIMEOUT_ERROR = "EVENT_TIMEOUT_ERROR"
    EVENT_HANDLER_ERROR = "EVENT_HANDLER_ERROR"
    EVENT_ACK_ERROR = "EVENT_ACK_ERROR"
    EVENT_NACK_ERROR = "EVENT_NACK_ERROR"
    EVENT_PROCESSING_ERROR = "EVENT_PROCESSING_ERROR"
    EVENT_REGISTERATION_ERROR = "EVENT_REGISTERATION_ERROR"

    # API Errors
    API_CONNECTION_ERROR = "API_CONNECTION_ERROR"
    API_TIMEOUT_ERROR = "API_TIMEOUT_ERROR"
    API_AUTHENTICATION_ERROR = "API_AUTHENTICATION_ERROR"
    API_AUTHORIZATION_ERROR = "API_AUTHORIZATION_ERROR"
    API_NOT_FOUND_ERROR = "API_NOT_FOUND_ERROR"
    API_METHOD_NOT_ALLOWED_ERROR = "API_METHOD_NOT_ALLOWED_ERROR"
    API_PAYLOAD_TOO_LARGE_ERROR = "API_PAYLOAD_TOO_LARGE_ERROR"
    API_UNSUPPORTED_MEDIA_TYPE_ERROR = "API_UNSUPPORTED_MEDIA_TYPE_ERROR"
    API_VALIDATION_ERROR = "API_VALIDATION_ERROR"
    API_SERVER_ERROR = "API_SERVER_ERROR"
    API_SERVICE_UNAVAILABLE_ERROR = "API_SERVICE_UNAVAILABLE_ERROR"
    API_RATE_LIMIT_ERROR = "API_RATE_LIMIT_ERROR"

    
    # Driver Errors
    VEHICLE_SUBMISSION_ERROR = "VEHICLE_SUBMISSION_ERROR"
    VEHICLE_GET_ERROR = "VEHICLE_GET_ERROR"
    VEHICLE_REMOVE_ERROR = "VEHICLE_REMOVE_ERROR"
    VEHICLE_MODIFY_ERROR = "VEHICLE_MODIFY_ERROR"
    VEHICLE_NOT_FOUND_ERROR = "VEHICLE_NOT_FOUND_ERROR"
    VEHICLE_PERMISSION_DENIED_ERROR = "VEHICLE_PERMISSION_DENIED_ERROR"
    VEHICLE_VALIDATION_ERROR = "VEHICLE_VALIDATION_ERROR"
    VEHICLE_SERVICE_UNAVAILABLE_ERROR = "VEHICLE_SERVICE_UNAVAILABLE_ERROR"
    
    @classmethod
    def get_error_code(cls, error_code):
        return getattr(cls, error_code, cls.UNKNOWN_ERROR)
